public with sharing class RunescapeHighscore {
    
    public String name;
    public Integer slayer;
    public Integer mining;
    public Integer farming;

    public void setName(String stri1){
        name = stri1;
    }

    public void setSlayer(Integer int1){
        slayer = int1;
    }

    public void setMining(Integer int2){
        mining = int2;
    }

    public void setFarming(Integer int3){
        farming = int3;
    }

}